apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gitlab
  namespace: gitlab
data:
  gitlab.rb: |
    external_url 'http://192.168.56.110:80'
    gitlab_rails['initial_root_password'] = "ThisIsMyPassword42"
    puma['per_worker_max_memory_mb'] = 2048
    gitlab_rails['env'] = {
      'GITLAB_RAILS_RACK_TIMEOUT' => 600
    }
